const express = require('express');
const router = express.Router();
const catalogController = require('../controllers/catalogController');
const queryController = require('../controllers/queryController');
const ingestController = require('../controllers/ingestController');
const { ingestLimiter } = require('../middleware/rateLimits');
router.get('/:id', catalogController.getResource);
router.get('/:id/query', queryController.queryResource);
router.post('/:id/ingest', ingestLimiter, ingestController.enqueueIngest);
module.exports = router;
