jest.mock('../db/catalogReadQueries', () => ({
    searchDatasets: jest.fn(),
    getDatasetByIdOrName: jest.fn(),
    listResourcesForDataset: jest.fn(),
    getResourceById: jest.fn(),
    listOrganizations: jest.fn(),
    getStats: jest.fn(),
    countSitemapDatasets: jest.fn(),
    listDatasetSitemap: jest.fn(),
    countSitemapResources: jest.fn(),
    listResourceSitemap: jest.fn(),
    listPlaceSitemap: jest.fn(),
    getPlaceByIdOrSlug: jest.fn(),
    pingDb: jest.fn(),
    getLastSyncTime: jest.fn(),
    listRecentlyIngested: jest.fn(),
    getJobHealth: jest.fn(),
}));
jest.mock('../services/ckanClient', () => ({ packageList: jest.fn(), packageSearch: jest.fn(), packageShow: jest.fn(), organizationList: jest.fn(), datastoreSearch: jest.fn() }));
jest.mock('../db/storeQueries', () => ({ queryStoreTable: jest.fn(), aggregateStoreTable: jest.fn(), touchLastAccessed: jest.fn(() => Promise.resolve()), TABLE_NAME_RE: /^r_[0-9a-f_]+$/ }));
jest.mock('../db/queryLogQueries', () => ({ logQueryHit: jest.fn(() => Promise.resolve()), listPopularResources: jest.fn(), countOlderThan: jest.fn(), pruneOlderThan: jest.fn() }));

const request = require('supertest');
const catalogRead = require('../db/catalogReadQueries');
const app = require('../app');
const { resolveMeta, injectAnalytics } = require('../controllers/spaController');

beforeEach(() => { jest.clearAllMocks(); });

describe('robots.txt', () => {
    it('allows all and points at the sitemap index', async () => {
        const res = await request(app).get('/robots.txt');
        expect(res.status).toBe(200);
        expect(res.headers['content-type']).toMatch(/text\/plain/);
        expect(res.text).toContain('User-agent: *');
        expect(res.text).toContain('Sitemap: https://canquery.com/sitemap.xml');
    });
});

describe('sitemap index', () => {
    it('lists one chunk per 25k quality-gated datasets and resources', async () => {
        catalogRead.countSitemapDatasets.mockResolvedValue(30000);
        catalogRead.countSitemapResources.mockResolvedValue(26000);
        const res = await request(app).get('/sitemap.xml');
        expect(res.status).toBe(200);
        expect(res.headers['content-type']).toMatch(/xml/);
        expect(res.text).toContain('<loc>https://canquery.com/sitemap-pages.xml</loc>');
        expect(res.text).toContain('<loc>https://canquery.com/sitemap-places.xml</loc>');
        expect(res.text).toContain('<loc>https://canquery.com/sitemap-datasets-1.xml</loc>');
        expect(res.text).toContain('<loc>https://canquery.com/sitemap-datasets-2.xml</loc>');
        expect(res.text).not.toContain('sitemap-datasets-3.xml');
        expect(res.text).toContain('<loc>https://canquery.com/sitemap-resources-1.xml</loc>');
        expect(res.text).toContain('<loc>https://canquery.com/sitemap-resources-2.xml</loc>');
        expect(res.text).not.toContain('sitemap-resources-3.xml');
    });

    it('always emits a dataset chunk but omits empty resource chunks', async () => {
        catalogRead.countSitemapDatasets.mockResolvedValue(0);
        catalogRead.countSitemapResources.mockResolvedValue(0);
        const res = await request(app).get('/sitemap.xml');
        expect(res.text).toContain('sitemap-datasets-1.xml');
        expect(res.text).not.toContain('sitemap-resources-1.xml');
    });
});

describe('pages sitemap', () => {
    it('includes the home and section hubs', async () => {
        const res = await request(app).get('/sitemap-pages.xml');
        expect(res.status).toBe(200);
        expect(res.text).toContain('<loc>https://canquery.com/</loc>');
        expect(res.text).toContain('<loc>https://canquery.com/insights</loc>');
        expect(res.text).toContain('<loc>https://canquery.com/privacy</loc>');
    });
});

describe('analytics configuration injection', () => {
    const template = '<head><!-- analytics:config --></head>';

    it('injects only a valid website id into the static bootstrap marker', () => {
        const id = '123e4567-e89b-42d3-a456-426614174000';
        expect(injectAnalytics(template, id)).toContain('content="' + id + '"');
        expect(injectAnalytics(template, '" /><script>bad</script>')).toBe('<head></head>');
    });

    it('accepts UUIDv7 website ids generated by the analytics service', () => {
        const id = '01a02c60-cd0a-77f4-8680-7e9e317534a1';
        expect(injectAnalytics(template, id)).toContain('content="' + id + '"');
    });

    it('removes the marker when analytics is not configured', () => {
        expect(injectAnalytics(template, '')).toBe('<head></head>');
    });
});

describe('dataset sitemap chunk', () => {
    it('emits a url per dataset using its slug + lastmod, id as fallback', async () => {
        catalogRead.listDatasetSitemap.mockResolvedValue([
            { id: 'd1', name: 'water-quality', metadata_modified: '2026-01-02T00:00:00Z' },
            { id: 'd2', name: null, metadata_modified: null },
        ]);
        const res = await request(app).get('/sitemap-datasets-1.xml');
        expect(res.status).toBe(200);
        expect(catalogRead.listDatasetSitemap).toHaveBeenCalledWith({ limit: 25000, offset: 0 });
        expect(res.text).toContain('<loc>https://canquery.com/datasets/water-quality</loc>');
        expect(res.text).toContain('<lastmod>2026-01-02T00:00:00.000Z</lastmod>');
        expect(res.text).toContain('<loc>https://canquery.com/datasets/d2</loc>');
    });

    it('computes the offset from the chunk number', async () => {
        catalogRead.listDatasetSitemap.mockResolvedValue([{ id: 'd9', name: 'x', metadata_modified: null }]);
        await request(app).get('/sitemap-datasets-3.xml');
        expect(catalogRead.listDatasetSitemap).toHaveBeenCalledWith({ limit: 25000, offset: 50000 });
    });

    it('404s past the last chunk', async () => {
        catalogRead.listDatasetSitemap.mockResolvedValue([]);
        const res = await request(app).get('/sitemap-datasets-99.xml');
        expect(res.status).toBe(404);
    });
});

describe('resource sitemap chunk', () => {
    it('emits canonical resource urls with parent-dataset lastmod values', async () => {
        catalogRead.listResourceSitemap.mockResolvedValue([
            { id: 'r1', metadata_modified: '2026-08-27T12:00:00Z' },
            { id: 'r/2', metadata_modified: null }
        ]);
        const res = await request(app).get('/sitemap-resources-1.xml');
        expect(res.status).toBe(200);
        expect(res.headers['content-type']).toMatch(/xml/);
        expect(catalogRead.listResourceSitemap).toHaveBeenCalledWith({ limit: 25000, offset: 0 });
        expect(res.text).toContain('<loc>https://canquery.com/resources/r1</loc>');
        expect(res.text).toContain('<lastmod>2026-08-27T12:00:00.000Z</lastmod>');
        expect(res.text).toContain('<loc>https://canquery.com/resources/r%2F2</loc>');
    });

    it('computes chunk offsets and 404s beyond the current resource set', async () => {
        catalogRead.listResourceSitemap
            .mockResolvedValueOnce([{ id: 'r9', metadata_modified: null }])
            .mockResolvedValueOnce([]);
        await request(app).get('/sitemap-resources-3.xml');
        expect(catalogRead.listResourceSitemap).toHaveBeenNthCalledWith(1, {
            limit: 25000,
            offset: 50000
        });
        const res = await request(app).get('/sitemap-resources-99.xml');
        expect(res.status).toBe(404);
    });

    it('rejects malformed chunk numbers without querying the catalogue', async () => {
        const res = await request(app).get('/sitemap-resources-1x.xml');
        expect(res.status).toBe(404);
        expect(catalogRead.listResourceSitemap).not.toHaveBeenCalled();
    });
});

describe('place sitemap', () => {
    it('emits only place rows supplied by the active-dataset query', async () => {
        catalogRead.listPlaceSitemap.mockResolvedValue([
            { slug: 'oshawa-on', metadata_modified: '2026-08-01T00:00:00Z' },
            { slug: 'ottawa-on', metadata_modified: '2026-08-23T00:00:00Z' }
        ]);
        const res = await request(app).get('/sitemap-places.xml');
        expect(res.status).toBe(200);
        expect(res.text).toContain('<loc>https://canquery.com/places/oshawa-on</loc>');
        expect(res.text).toContain('<loc>https://canquery.com/places/ottawa-on</loc>');
        expect(res.text).toContain('<lastmod>2026-08-01T00:00:00.000Z</lastmod>');
    });
});

describe('resolveMeta routing', () => {
    it('resolves a dataset via the DB and includes Dataset JSON-LD', async () => {
        const deps = {
            getDatasetByIdOrName: jest.fn().mockResolvedValue({ id: 'd1', name: 'n1', title_en: 'T', notes_en: 'N' }),
            listResourcesForDataset: jest.fn().mockResolvedValue([]),
            getResourceById: jest.fn(),
        };
        const meta = await resolveMeta('/datasets/n1', deps);
        expect(deps.getDatasetByIdOrName).toHaveBeenCalledWith('n1');
        expect(meta.title).toBe('T - canquery');
        expect(meta.jsonLd[0]['@type']).toBe('Dataset');
    });

    it('returns noindex not-found meta for an unknown dataset (no resource lookup)', async () => {
        const deps = {
            getDatasetByIdOrName: jest.fn().mockResolvedValue(null),
            listResourcesForDataset: jest.fn(),
            getResourceById: jest.fn(),
        };
        const meta = await resolveMeta('/datasets/ghost', deps);
        expect(meta.noindex).toBe(true);
        expect(deps.listResourcesForDataset).not.toHaveBeenCalled();
    });

    it('resolves a resource page', async () => {
        const deps = {
            getResourceById: jest.fn().mockResolvedValue({
                id: 'r1', dataset_id: 'd1', dataset_name: 'dataset-slug',
                name_en: 'File', format: 'CSV', dataset_title_en: 'DS'
            }),
            getDatasetByIdOrName: jest.fn(),
            listResourcesForDataset: jest.fn(),
        };
        const meta = await resolveMeta('/resources/r1', deps);
        expect(meta.title).toBe('DS (CSV) - canquery');
        expect(meta.canonical).toBe('https://canquery.com/resources/r1');
        expect(meta.jsonLd[0].itemListElement[1].item).toBe('https://canquery.com/datasets/dataset-slug');
    });

    it('resolves a place page from its stable slug', async () => {
        const deps = {
            getPlaceByIdOrSlug: jest.fn().mockResolvedValue({
                id: 'ca-on-oshawa', slug: 'oshawa-on', name_en: 'Oshawa', type_en: 'City',
                ancestors: [{ id: 'ca-on-oshawa', slug: 'oshawa-on', name_en: 'Oshawa' }]
            })
        };
        const meta = await resolveMeta('/places/oshawa-on', deps);
        expect(deps.getPlaceByIdOrSlug).toHaveBeenCalledWith('oshawa-on');
        expect(meta.title).toContain('Oshawa');
        expect(meta.noindex).not.toBe(true);
        expect(meta.jsonLd.some(item => item['@type'] === 'BreadcrumbList')).toBe(true);
    });

    it('uses static home meta without touching the DB', async () => {
        const deps = { getDatasetByIdOrName: jest.fn(), listResourcesForDataset: jest.fn(), getResourceById: jest.fn() };
        const meta = await resolveMeta('/', deps);
        expect(meta.jsonLd.some((o) => o['@type'] === 'WebSite')).toBe(true);
        expect(deps.getDatasetByIdOrName).not.toHaveBeenCalled();
    });
});
